import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    // Components
    "components/accordion": "src/components/accordion.tsx",
    "components/alert-dialog": "src/components/alert-dialog.tsx",
    "components/alert": "src/components/alert.tsx",
    "components/aspect-ratio": "src/components/aspect-ratio.tsx",
    "components/avatar": "src/components/avatar.tsx",
    "components/badge": "src/components/badge.tsx",
    "components/breadcrumb": "src/components/breadcrumb.tsx",
    "components/button": "src/components/button.tsx",
    "components/calendar": "src/components/calendar.tsx",
    "components/card": "src/components/card.tsx",
    "components/carousel": "src/components/carousel.tsx",
    "components/chart": "src/components/chart.tsx",
    "components/checkbox": "src/components/checkbox.tsx",
    "components/collapsible": "src/components/collapsible.tsx",
    "components/command": "src/components/command.tsx",
    "components/context-menu": "src/components/context-menu.tsx",
    "components/dialog": "src/components/dialog.tsx",
    "components/drawer": "src/components/drawer.tsx",
    "components/dropdown-menu": "src/components/dropdown-menu.tsx",
    "components/form": "src/components/form.tsx",
    "components/hover-card": "src/components/hover-card.tsx",
    "components/input-otp": "src/components/input-otp.tsx",
    "components/input": "src/components/input.tsx",
    "components/label": "src/components/label.tsx",
    "components/menubar": "src/components/menubar.tsx",
    "components/multi-select": "src/components/multi-select.tsx",
    "components/navigation-menu": "src/components/navigation-menu.tsx",
    "components/popover": "src/components/popover.tsx",
    "components/progress": "src/components/progress.tsx",
    "components/radio-group": "src/components/radio-group.tsx",
    "components/resizable": "src/components/resizable.tsx",
    "components/scroll-area": "src/components/scroll-area.tsx",
    "components/select": "src/components/select.tsx",
    "components/separator": "src/components/separator.tsx",
    "components/sheet": "src/components/sheet.tsx",
    "components/sidebar": "src/components/sidebar.tsx",
    "components/skeleton": "src/components/skeleton.tsx",
    "components/slider": "src/components/slider.tsx",
    "components/sonner": "src/components/sonner.tsx",
    "components/switch": "src/components/switch.tsx",
    "components/table": "src/components/table.tsx",
    "components/tabs": "src/components/tabs.tsx",
    "components/textarea": "src/components/textarea.tsx",
    "components/toast": "src/components/toast.tsx",
    "components/toaster": "src/components/toaster.tsx",
    "components/toggle": "src/components/toggle.tsx",
    "components/toggle-group": "src/components/toggle-group.tsx",
    "components/tooltip": "src/components/tooltip.tsx",
    "components/pagination": "src/components/pagination.tsx",
    
    // Lib files
    "lib/utils": "src/lib/utils.ts",
    
    // Hooks
    "hooks/use-toast": "src/hooks/use-toast.ts"
  },
  format: ["esm", "cjs"],
  dts: {
    compilerOptions: {
      moduleResolution: "bundler",
      baseUrl: ".",
      paths: {
        "@repo/ui/*": ["./src/*"]
      },
      composite: false,
      incremental: false,
      tsBuildInfoFile: undefined
    },
    resolve: true,
    entry: {
      "components/accordion": "src/components/accordion.tsx",
      "components/alert-dialog": "src/components/alert-dialog.tsx",
      "components/alert": "src/components/alert.tsx",
      "components/aspect-ratio": "src/components/aspect-ratio.tsx",
      "components/avatar": "src/components/avatar.tsx",
      "components/badge": "src/components/badge.tsx",
      "components/breadcrumb": "src/components/breadcrumb.tsx",
      "components/button": "src/components/button.tsx",
      "components/calendar": "src/components/calendar.tsx",
      "components/card": "src/components/card.tsx",
      "components/carousel": "src/components/carousel.tsx",
      "components/chart": "src/components/chart.tsx",
      "components/checkbox": "src/components/checkbox.tsx",
      "components/collapsible": "src/components/collapsible.tsx",
      "components/command": "src/components/command.tsx",
      "components/context-menu": "src/components/context-menu.tsx",
      "components/dialog": "src/components/dialog.tsx",
      "components/drawer": "src/components/drawer.tsx",
      "components/dropdown-menu": "src/components/dropdown-menu.tsx",
      "components/form": "src/components/form.tsx",
      "components/hover-card": "src/components/hover-card.tsx",
      "components/input-otp": "src/components/input-otp.tsx",
      "components/input": "src/components/input.tsx",
      "components/label": "src/components/label.tsx",
      "components/menubar": "src/components/menubar.tsx",
      "components/multi-select": "src/components/multi-select.tsx",
      "components/navigation-menu": "src/components/navigation-menu.tsx",
      "components/popover": "src/components/popover.tsx",
      "components/progress": "src/components/progress.tsx",
      "components/radio-group": "src/components/radio-group.tsx",
      "components/resizable": "src/components/resizable.tsx",
      "components/scroll-area": "src/components/scroll-area.tsx",
      "components/select": "src/components/select.tsx",
      "components/separator": "src/components/separator.tsx",
      "components/sheet": "src/components/sheet.tsx",
      "components/sidebar": "src/components/sidebar.tsx",
      "components/skeleton": "src/components/skeleton.tsx",
      "components/slider": "src/components/slider.tsx",
      "components/sonner": "src/components/sonner.tsx",
      "components/switch": "src/components/switch.tsx",
      "components/table": "src/components/table.tsx",
      "components/tabs": "src/components/tabs.tsx",
      "components/textarea": "src/components/textarea.tsx",
      "components/toast": "src/components/toast.tsx",
      "components/toaster": "src/components/toaster.tsx",
      "components/toggle": "src/components/toggle.tsx",
      "components/toggle-group": "src/components/toggle-group.tsx",
      "components/tooltip": "src/components/tooltip.tsx",
      "components/pagination": "src/components/pagination.tsx",
      "lib/utils": "src/lib/utils.ts",
      "hooks/use-toast": "src/hooks/use-toast.ts"
    }
  },
  clean: true,
  external: [
    "react",
    "react-dom",
    "@radix-ui/*",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "lucide-react",
    "cmdk",
    "next-themes",
    "react-day-picker",
    "date-fns",
    "embla-carousel-react",
    "recharts",
    "input-otp",
    "sonner",
    "vaul",
    "@hookform/resolvers",
    "react-hook-form",
    "react-resizable-panels",
    "zod"
  ],
  treeshake: true,
  splitting: true,
  sourcemap: true,
  minify: true,
  outDir: "dist"
}); 