global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'

  - job_name: 'adminka'
    static_configs:
      - targets: ['adminka:5173']
    metrics_path: '/metrics'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100'] 

  - job_name: 'discord_bot'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['discord-bot:3002']
